### PR TITLE
Ignore undefined linting of Py2 only globals in Py2 only code blocks.

### PR DESCRIPTION
**Pull request by rtibbles**
Fix erroneous Py3 linting errors.

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
THANKS! In the future, feel free to push straight to my PR branch :)

**Comment by rtibbles** [comment]
I tried that first, but it said that I wasn't authorised. I think github has disabled that feature, it seems?

**Comment by benjaoming** [comment]
I find that I have to:

1. Add user's repo as a remote
1. Push current branch to the repo with a special pattern: `git push <remote> HEAD:<remote-branch>`

**Comment by rtibbles** [comment]
Ah, I was doing everything but the HEAD:

**Pull request merged**
